[package]
name = "discord-tts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envy = "0.4.2"
once_cell = "1.13.0"
reqwest = { version = "0.11.11", features = ["rustls-tls"] , default-features = false }
serde = { version = "1.0.143" , features = ["derive"] }
serde_json = "1.0.83"
serenity = { version = "0.10.10", features = ["client", "standard_framework", "voice", "rustls_backend"] }
songbird = { version = "0.2.2", features = ["builtin-queue"] }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.36"
tracing-futures = "0.2.5"
tracing-subscriber = "0.3.15"
uuid = { version = "1.1.2", features = ["v4"] }
