version: '3.9'
services:
  voicevox:
    image: hiroshiba/voicevox_engine:nvidia-latest@sha256:3c250d6b9b52a604a5a56fc023b88d0cc3ed411062b0a9ab41d390e2266a8ed6
    hostname: voicevox
    container_name: discordtts__voicevox
    restart: always
    expose:
      - 50021

    networks:
      - voicevox_discordtts

    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

  discordtts:
    build: .
    image: discordtts
    hostname: discordtts
    container_name: discordtts__discordtts
    depends_on:
      - voicevox

    restart: always

    environment:
      VOICEVOX_HOST: http://voicevox:50021
      STATE_PATH: /var/discordtts/state.json
      TMP_PATH: /tmp/
      DISCORD_TOKEN: ${DISCORD_TOKEN}

    volumes:
      - type: volume
        source: data
        target: /var/discordtts/

    networks:
      - voicevox_discordtts
      - discordtts_internet

    deploy:
      resources:
        limits:
          memory: 512m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

volumes:
  data:
    name: discordtts__data

networks:
  voicevox_discordtts:
    name: discordtts__voicevox_discordtts
    internal: true

  discordtts_internet:
    name: discordtts__discordtts_internet
