name: hadolint

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.36.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
