name: hadolint

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.42.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
