name: hadolint

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.41.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
